//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passwordreset
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public string Token { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public Nullable<int> IsExpired { get; set; }
    
        public virtual User User { get; set; }
    }
}
